site_name: maestro
site_url: https://roboflow.github.io/multimodal-maestro/
site_author: Roboflow
site_description: 'Streamline the fine-tuning process for multimodal models: PaliGemma, Florence-2, Qwen2-VL.'
repo_name: roboflow/multimodal-maestro
repo_url: https://github.com/roboflow/multimodal-maestro
edit_uri: https://github.com/roboflow/multimodal-maestro/tree/main/docs
copyright: Roboflow 2024. All rights reserved.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/roboflow
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/roboflow
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/roboflow-ai/mycompany/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/roboflow

nav:
  - Maestro: index.md
  - Reference - Code API:
    - Models:
      - Florence-2: florence-2.md
    - Tasks: tasks.md
    - Metrics: metrics.md
  - Release Notes: changelog.md


theme:
  name: 'material'
  logo: https://media.roboflow.com/open-source/supervision/supervision-lenny.png
  favicon: https://media.roboflow.com/open-source/supervision/supervision-lenny.png
  custom_dir: docs/theme
  palette:
    # Palette for light mode
    - scheme: default
      primary: 'custom'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: 'custom'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
